### ISSUE TITLE
Coverage display is limited in [-0.06:0.06]

### ISSUE THREAD

**Issue by xunhuazhao** [mhoffman/kmos#19]
I just started to learn kmos. The installation seems fine, while in the test (of the examples in the package), I found in the GUI panel created by "kmos view", only when the coverage is smaller than 0.06, the curve (of, say, empty sites) is shown. Ps: in the parameter arguments, the min and max are set. Anyone knows the problem? Thanks a lot.

**Comment by mhoffman** [comment]
You could create a minimal model that reproduces the problem and drop it in
a gist[1].

[1] https://gist.github.com/

2015-03-01 11:41 GMT-08:00 xunhuazhao <notifications@github.com>:

> I just started to learn kmos. The installation seems fine, while in the
> test (of the examples in the package), I found in the GUI panel created by
> "kmos view", only when the coverage is smaller than 0.06, the curve (of,
> say, empty sites) is shown. Ps: in the parameter arguments, the min and max
> are set. Anyone knows the problem? Thanks a lot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mhoffman/kmos/issues/19>.
>



-- 
Dr. Max J. Hoffmann
MAIL
Dept. of Chemical Engineering              PHONE:  +1 650 521 7187
Stanford University                                EMAIL:
maxjh@stanford.edu
4300
Shriram Center, room 315
443 Via Ortega
Stanford, CA 94035-4125
(U.S.A.)

**Comment by xunhuazhao** [comment]
Hi, sorry that I do not full get what you meant. I simply used the AB_model (and other models) for test purpose. Could you tell me which file I should drop in gist?

BTW, I found that all but one dependence I have not install sucessfully--"gazpacho". Actually, there seems some problem with the gazpacho repository--have a look at this site: https://apps.ubuntu.com/cat/applications/gazpacho/

Thanks a lot!

**Comment by mhoffman** [comment]
Just fixed the y-range issue in the occupation plot. Thanks for the heads-up.

As for the gazpacho installation part: I know that gazpacho is a problematic dependency. And I think this is really unfortunate since the editor GUI is such a useful tool for debugging a process list. However I did not find a clear upgrade path to update the glade files to something compatible with GTK3. Also I do not have the time and resources to upgrade the whole GUI to a new toolkit (let alone the question: which one should we actually pick?). So for now the answer is: try to install gazpacho wherever you develop the model. You will not need it later for running the model. You could e.g. install the whole development environment on a virtual machine ... also have you seen the pointers here[1]? Have you actually run into problems installing gazpacho on your machine? I.e. does it break other packages you are using?


[1] http://kmos.readthedocs.org/en/latest/tutorials/index.html?highlight=gazpacho

**Comment by mhoffman** [comment]
Since I haven't heard otherwise I assume my patch has resolved the issue.

**Comment by xunhuazhao** [comment]
Yes, the problem of y-range is solved. Sorry for late response.
Thank you very much!

**Comment by xunhuazhao** [comment]
Hi, concerning the gazpacho installation, I tried the way in the manual many times, the message is always like 
"Package gazpacho is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source 
E: Package 'gazpacho' has no installation candidate
".
I also tried to download the package and install manually, it did not work too.
