### ISSUE TITLE
Myfrist_kMC.xml file

### ISSUE THREAD

**Issue by topaztm** [mhoffman/kmos#20]
(1) I have already export Myfrist_kMC.xml but i dont know how to use it ?
and (2) How can i use the command 'kmos view' ?
Thank you

**Comment by mhoffman** [comment]
hanks for your inquiry and your interest in kmos. The short answer is that whatever you are trying to achieve with kMC/kMOS it will be easier on Linux or a Mac but not Windows. Especially in the mid- to long-term. Most ground breaking computational/theoretical research I am aware of simply doesn't happen on Windows. Even though in theory it is possible to run kMOS on Windows (I have done so before) most of the tutorials will not make sense from within Windows

Having exported your *.xml file sounds great. Can you ensure that it actually compiled the model correctly? If so you should see a folder like Myfrist_kMC or Myfrist_kMC_local_smart in the same  directory and inside two files called kmc_settings.py and kmc_model.pyd or something like that. In this directory you should run 'kmos view' from a shell. You are using a shell? Executing 'kmos view' in there should fire one window showing the surface geometry and another plotting window showing coverages and rates in real time. That however is usually just the first step, you should then for instance run 'kmos shell' and start playing with the API which will result in your own scripts that you can use to run an analyze rates and coverages from your model.

If this sounds complicated, frankly the problem is that most Monte Carlo techniques are difficult to do if your intention is to do absolutely zero programming. The frameworks that are emerging are still in a fairly early stage (including kmos). And can usually cover only a core set of model features and sampling techniques. Whenever you are interested in more exotic properties or model types, having some programming experience will be quite useful if not essential. So, if you try to work with the documentation (plus maybe Linux, Python, shell)  you might learn a lot in the process. Also here I highly recommend checking out the lectures over at http://software-carpentry.org/.
