### ISSUE TITLE
.bumpversion.cfg

### ISSUE THREAD

**Issue by jmlorenzi** [mhoffman/kmos#30]
Why is the version number in that file in the develop branch behind the master branch?
Is that expected behaviour? I would have expected either that they match or the reverse...

I am asking this because I am trying to improve my git-workflow and I think develop lagging behind master complicates this. I.e.

branch hotfix-branch from master
... fix bug ...
merge hotfix-branch into master
merge hotfix-branch into develop ## Here git will want to also bump the version

Cheers,
Juan

**Comment by mhoffman** [comment]
As a simple rule: always bump exactly master when you have merged into it.

In an ideal world the develop branch would not have a .bumpversion.cfg at all. It is probably only the due to some superfluous merge from master into develop. So just consider the .bumpversion.config in develop an anachronism that doesn't do anything. The version has to be bumped whenever develop merges into master or when hotfix_*** merges into master. So simply merge the hotfix into develop and master but bump the version only on master.
