### ISSUE TITLE
kind_values_f2py.f90 not genereated properly?

### ISSUE THREAD

**Issue by vrulg** [mhoffman/kmos#33]
Hi, 

I've just tried installing your code and setting up the example model. I think it's not generating the kind_values file properly. I'm working in Windows Vista at the moment, which, it just occurred to me, may be the problem? Maybe there's something in the code that looks specifically for win 7?

Inside kind_values_f2py.f90 is just 
!/* ROBODOC this makes robodoc to document this file */
module kind_values
!****h* libkmc/kind_values
! FUNCTION
!    This module offers kind_values for commonly
!    used intrinsic types in a platform independent way.
!******
implicit none

and the kmos export command out put ends with 

gfortran.exe:f90: kind_values_f2py.f90
Error: Unexpected end of file in 'kind_values_f2py.f90'
error: Command "C:\MinGW\bin\gfortran.exe -ffree-line-length-none -ffree-form -xf95-cpp-input -Wall -O3 -fimplicit-none-O3 -funroll-loops -Ic:\users\user_name\appdata\local\temp\tmplpyh2r\src.win32-2.7 -Ic:\users\user_name\appdata\local\enthought\canopy32\user\lib\site-packages\numpy\core\include -IC:\Users\user_name\AppData\Local\Enthought\Canopy32\App\appdata\canopy-1.5.2.2785.win-x86\include -Ic:\users\user_name\appdata\local\enthought\canopy32\user\PC -c -c kind_values_f2py.f90 -o c:\users\user_name\appdata\local\temp\tmplpyh2r\Release\kind_values_f2py.o -Jc:\users\user_name\appdata\local\temp\tmplpyh2r\Release\ -Ic:\users\user_name\appdata\local\temp\tmplpyh2r\Release\" failed with exit status 1

**Comment by mhoffman** [comment]
Ideally this step would work in Windows (seriously?) as well, but of course it is not as well tested nor maintained there. What clutter of error you are seeing could be the result of a ton of of different sources. If it is just that file you could copy the kind_values.f90 over kind_values_f2py.f90 and replace the kind values for your combination of architecture/compiler by hand. And then build the code using 'kmos build' again.

But as I said this may have a ton of other reasons and it may be either to try it again on Linux of Mac OS X. Also you should remove the folder you export to every time you start over because the export may skip that kind_values translation step if a (broken) file already exists.
